FROM elasticsearch:alpine

MAINTAINER HyanCat <hyancat@live.cn>

RUN elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v5.5.1/elasticsearch-analysis-ik-5.5.1.zip
